image: ubuntu:18.04

variables:
    BINARY_TARBALL: "$CI_PROJECT_DIR/LibreWolf.tar.bz2"
    APPIMAGE_FILE: "$CI_PROJECT_DIR/LibreWolf.AppImage"
    FLATPAK_REPO: "$CI_PROJECT_DIR/librewolf-flatpak-repo"
    FLATPAK_BUNDLE: "$CI_PROJECT_DIR/LibreWolf.flatpak"

stages:
  - Build
  - Package
  - Deploy

Build Tarball:
    stage: Build
    tags: [librewolf]
    script:
        - $CI_PROJECT_DIR/binary_tarball/build_tarball.sh $BINARY_TARBALL
    artifacts:
        name: "Librewolf-$CI_COMMIT_REF_NAME-Linux-Tarball"
        paths:
            - "$BINARY_TARBALL"

Build AppImage:
    stage: Package
    tags: [gitlab-org]
    script:
        - $CI_PROJECT_DIR/appimage/build_appimage.sh $BINARY_TARBALL $APPIMAGE_FILE
    artifacts:
        name: "Librewolf-$CI_COMMIT_REF_NAME-Linux-Appimage"
        paths:
            - "$APPIMAGE_FILE"

Build Flatpak:
    image: black0/flatpak
    stage: Package
    tags:
        - gitlab-org
    script:
        - $CI_PROJECT_DIR/flatpak/build_flatpak.sh $BINARY_TARBALL $FLATPAK_REPO $FLATPAK_BUNDLE
    artifacts:
        name: "Librewolf-$CI_COMMIT_REF_NAME-Linux-Flatpak"
        paths:
            - "$FLATPAK_REPO"
            - "$FLATPAK_BUNDLE"

Release to Gitlab:
  stage: Deploy
  image: python3
  script:
    - pip3 install gitlab-release
    - gitlab-release LibreWolf.tar.bz2 LibreWolf.AppImage librewolf-flatpak-repo LibreWolf.flatpak
  only:
    - tags
